stock_handler:
  ros__parameters:
    start:
      pose:
        x: -0.475
        y: -0.3
        z: 0.0
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
      frame: optical_table_back_right_bolt
    attach:
      pose:
        x: 0
        y: 0
        z: 0.001
        qx: 0.0
        qy: 1.0
        qz: 0.0
        qw: 6.12e-17
        frame: gripper_jaw_centre
    stock_frame: implant
