controller_names:
  - fake_iiwa_controller
  - fake_gripper_controller
fake_iiwa_controller:
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
fake_gripper_controller:
    joints:
      - gripper_joint_left
