fake_joint_driver_node:
  ros__parameters:
    start_position:
      joints:
        - iiwa_joint_1
        - iiwa_joint_2
        - iiwa_joint_3
        - iiwa_joint_4
        - iiwa_joint_5
        - iiwa_joint_6
        - iiwa_joint_7
      values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
    include_joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
    exclude_joints:
      - gripper_joint_left
      - gripper_joint_right

