<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="cutting_plate" params="blade_height:=^|0.0025">
<!--    <xacro:arg name="blade_height" default="0.0025"/>-->
    <xacro:property name="intersection_offset" value="0.00026" /> <!-- If there is a chisel tip this is the offset to the intersection point of the edges-->
    <link name="us_cutter_enclosure">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ram_support/meshes/tools/visual/us_cutter_enclosure.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${-pi/2}"/>
        <geometry>
          <mesh filename="package://ram_support/meshes/tools/collision/collision_us_cutter_enclosure.stl"/>
        </geometry>
      </collision>
    </link>

    <link name="cutting_plate_base">
<!--      <visual>-->
<!--        <origin xyz="0 0 -0.005" rpy="0 0 0"/>-->
<!--        <geometry>-->
<!--            <box size="0.315 0.315 0.01" />-->
<!--        </geometry>-->
<!--      </visual>-->

      <collision>
        <origin xyz="0 0 -0.005" rpy="0 0 ${-pi/2}"/>
        <geometry>
            <box size="0.315 0.315 0.01" />
        </geometry>
      </collision>
    </link>

    <joint name="us_cutter_surface_joint" type="fixed">
      <parent link="us_cutter_enclosure"/>
      <child link="cutting_plate_base"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

  <!-- Cutting tool selected-->
    <link name="cutting_tool">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ram_support/meshes/tools/visual/DUK8.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ram_support/meshes/tools/collision/DUK8.stl"/>
        </geometry>
      </collision>
    </link>

    <link name="cutting_tool_base"/>
    <link name="cutting_tool_tip"/>

    <joint name="cutting_tool_joint" type="fixed">
      <parent link="cutting_plate_base"/>
      <child link="cutting_tool"/>
      <origin xyz="0.017 0 ${-0.0087 + blade_height}" rpy="0 0 0"/>
    </joint>

    <joint name="cutting_tool_base_joint" type="fixed">
      <parent link="cutting_tool"/>
      <child link="cutting_tool_base"/>
      <origin xyz="${(blade_height + intersection_offset) * tan(30 * pi / 180)} 0 ${0.0087 - blade_height}" rpy="0 0 0"/>
    </joint>

    <joint name="cutting_tool_tip_joint" type="fixed">
      <parent link="cutting_tool"/>
      <child link="cutting_tool_tip"/>
      <origin xyz="0 0 0.0087" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

</robot>